DROP TABLE IF EXISTS users_added CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS review_requests CASCADE;
DROP TABLE IF EXISTS userSettings CASCADE;
DROP TABLE IF EXISTS custom_prompt CASCADE;